blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community Forum
    url: https://community.home-assistant.io/
    about: Ask questions and get help from the Home Assistant community
  - name: Documentation
    url: https://github.com/pnbruckner/ha-life360/blob/master/README.md
    about: Read the documentation before opening an issue
